### ISSUE TITLE
Enlever tous les marqueurs //TODO auto-générés par Eclipse et qui servent pas à grand chose

### ISSUE THREAD

**Issue by BSMehdi** [nruffier/AdamingImmo#3]
- [x] https://github.com/nruffier/AdamingImmo/blob/8c4fade344860b2c975db4f8b272ada7dd89f9af/src/main/java/com/fr/adaming/service/impl/BienServiceImpl.java#L31
- [x] https://github.com/nruffier/AdamingImmo/blob/8c4fade344860b2c975db4f8b272ada7dd89f9af/src/main/java/com/fr/adaming/service/impl/BienServiceImpl.java#L48
- [x] https://github.com/nruffier/AdamingImmo/blob/8c4fade344860b2c975db4f8b272ada7dd89f9af/src/main/java/com/fr/adaming/service/impl/BienServiceImpl.java#L64
- [x] https://github.com/nruffier/AdamingImmo/blob/8c4fade344860b2c975db4f8b272ada7dd89f9af/src/main/java/com/fr/adaming/service/impl/BienServiceImpl.java#L81
- [x] https://github.com/nruffier/AdamingImmo/blob/8c4fade344860b2c975db4f8b272ada7dd89f9af/src/main/java/com/fr/adaming/service/impl/BienServiceImpl.java#L100

**Comment by nruffier** [comment]
https://github.com/nruffier/AdamingImmo/blob/11dba78a580ce4f14ca8f87f62a8fa6d587a906e/src/main/java/com/fr/adaming/entity/Bien.java#L57
